name = "VoronoiProject"
uuid = "d1e00843-67be-4db0-ae7b-4463c6f460a6"
authors = ["Chris Kyrill Hansen <hansen@campus.tu-berlin.de>"]
version = "0.1.0"

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Cairo = "1.1.1"
Colors = "0.12.11"
GLMakie = "0.4.5"
LinearAlgebra = "1.11.0"
Makie = "0.15.1"
Test = "1.11.0"
